/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lqr_opencv_tracker_HandTracker */

#ifndef _Included_com_lqr_opencv_tracker_HandTracker
#define _Included_com_lqr_opencv_tracker_HandTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lqr_opencv_tracker_HandTracker
 * Method:    initHandModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_lqr_opencv_tracker_HandTracker_initHandModel
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lqr_opencv_tracker_HandTracker
 * Method:    initCascadeClassifier
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_lqr_opencv_tracker_HandTracker_initCascadeClassifier
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lqr_opencv_tracker_HandTracker
 * Method:    checkHand
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_lqr_opencv_tracker_HandTracker_checkHand__JJ
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_lqr_opencv_tracker_HandTracker
 * Method:    checkHand
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_lqr_opencv_tracker_HandTracker_checkHand__JJJ
        (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_lqr_opencv_tracker_HandTracker
 * Method:    destroyHandModel
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_lqr_opencv_tracker_HandTracker_destroyHandModel
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lqr_opencv_tracker_HandTracker
 * Method:    destroyCascadeClassifier
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_lqr_opencv_tracker_HandTracker_destroyCascadeClassifier
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
